classification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
                  path('applications/', include('statistical_pnc.urls')),
                  path('', views.home_page_view, name='home'),
                  path('about-me', views.about_me_page_view, name='about_me'),
                  path('contact-me', views.contact_me_page_view, name='contact_me'),
                  path('sample', views.sample_page_view, name='sample'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statistical_pnc/urls.py
from django.urls import path, include

from .views import *

app_name = 'statistical_pnc'
urlpatterns = [
    path('news-classification', classification_index_view, name='news_classification_index'),
    path('news-classification/classification', classification_view, name='news_classification_classification'),
    path('news-classification/feedback', classification_feedback_view, name='news_classification_feedback'),
    path('news-classification/preprocessing', classification_preprocessing_view,
         name='news_classification_preprocessing'),

    path('keywords-extraction', keywords_extraction_view, name='keywords_extraction_index'),
    path('text-similarity', text_similarity_view, name='text_similarity_index'),
]

templates/base.html
<!--
=========================================================
* Neumorphism UI - v1.0.0
* Manipulated by nvd
=========================================================
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!-- Primary Meta Tags -->
    <title>PersianNLP{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--  Social tags -->
    <meta name="keywords"
          content="Persian Language, Persian Pre-Processing, Persian Text, Persian NaturalLanguageProcessing, NLP, Neural Networks, Deep Learning">

    <!-- Open Graph data -->
    <meta property="fb:app_id" content="214738555737136">
    <meta property="og:title" content="Neumorphism UI by Themesberg"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="https://demo.themesberg.com/neumorphism-ui/"/>
    <meta property="og:image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg"/>
    <meta property="og:description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages."/>
    <meta property="og:site_name" content="Themesberg"/>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="120x120" href="{% static './assets/img/favicon/nvd.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static './assets/img/favicon/nvd.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static './assets/img/favicon/nvd.png' %}">
    <link rel="manifest" href="{% static './assets/img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static './assets/img/favicon/safari-pinned-tab.svg' %}" color="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">


    <!-- Fontawesome -->
    <link type="text/css" href="{% static './vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

    <!-- Pixel CSS -->
    <link type="text/css" href="{% static './css/neumorphism.css' %}" rel="stylesheet">

    <!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->

</head>

<body>
<header class="header-global">
    <nav id="navbar-main" aria-label="Primary navigation"
         class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-light navbar-transparent navbar-theme-primary">
        <div class="container position-relative">
            <a class="navbar-brand shadow-soft py-2 px-3 rounded border border-light mr-lg-4" href="{% url 'home' %}">
                <img class="navbar-brand-dark" src="/static/assets/img/brand/dark.svg" alt="Logo light">
                <img class="navbar-brand-light" src="/static/assets/img/brand/dark.svg" alt="Logo dark">
            </a>
            <div class="navbar-collapse collapse" id="navbar_global">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="{% url 'home' %}"
                               class="navbar-brand shadow-soft py-2 px-3 rounded border border-light">
                                <img src="{% static 'assets/img/brand/dark.svg' %}" alt="Themesberg logo">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <a href="#navbar_global" class="fas fa-times" data-toggle="collapse"
                               data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="true"
                               title="close" aria-label="Toggle navigation"></a>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown">
                            <span class="nav-link-inner-text">Applications</span>
                            <span class="fas fa-angle-down nav-link-arrow ml-2"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'statistical_pnc:news_classification_index' %}">News
                                Classification</a></li>
                            <li><a class="dropdown-item" href="{% url 'statistical_pnc:keywords_extraction_index' %}">Keywords
                                Extraction</a></li>
                            <li><a class="dropdown-item" href="{% url 'statistical_pnc:text_similarity_index' %}">Text
                                Similarity</a></li>
                        </ul>
                    </li>
                    {% block header_for_application %}
                    {% endblock %}
                    <li><a class="dropdown-item" href="{% url 'about_me' %}">About me</a></li>
                    <li><a class="dropdown-item" href="{% url 'contact_me' %}">Contact me</a></li>
                </ul>
            </div>
            <div class="d-flex align-items-center">
                {% block resume_file %}
                {% endblock %}
                <button class="navbar-toggler ml-2" type="button" data-toggle="collapse" data-target="#navbar_global"
                        aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
</header>
<main>
    {% block info %}
        <!-- Section Info -->
        <section class="section bg-primary pb-0 section-lg">
            <div class="container z-2">
                <div class="row justify-content-center text-center pt-6">
                    <div class="col-lg-8 col-xl-8">
                        <h1 class="display-2 mb-3">{% block application_title %}{% endblock %}</h1>
                        <p class="lead px-md-6 mb-5">{% block application_content %}{% endblock %}</p>
                        {% block apllication_download_master %}
                            <div class="d-flex flex-column flex-wrap flex-md-row justify-content-md-center mb-5">
                                <a href="{% block application_download_href %}#{% endblock %}" target="_blank"
                                   class="btn btn-primary mb-3 mb-lg-0 mr-3"><i
                                        class="fas fa-cloud-download-alt mr-2"></i>
                                    Download </a>

                            </div>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </section>
        <!-- End of Info -->
    {% endblock %}
    {% block main_body %}
        <!-- Section Performance -->
        <section class="section bg-primary pt-0 section-lg" id="Performance">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-5">
                            <span class="font-weight-bold">Performance</span>
                        </div>
                    </div>
                </div>
                {% block performance_body %}{% endblock %}
            </div>
        </section>
        <!-- End of Performance -->

        <!-- Section Test -->
        <section class="section bg-primary pt-0 section-lg" id="Test">
            <div class="container">
                <!-- Title -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-5">
                            <span class="font-weight-bold">Test</span>
                        </div>
                    </div>
                </div>
                {% block test_body %}{% endblock %}
            </div>
        </section>
        <!-- End of Test -->
        <!-- Section api -->
        <section class="section bg-primary pt-0 section-lg" id="API">
            <div class="container">
                <!-- Title -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-5">
                            <span class="font-weight-bold">APIs</span>
                        </div>
                    </div>
                </div>
                {% block api_body %}{% endblock %}
            </div>
        </section>
        <!-- End of api -->
    {% endblock %}
</main>


<!-- Core -->
<script src="{% static './vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static './vendor/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static './vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static './vendor/headroom.js/dist/headroom.min.js' %}"></script>
<!-- Vendor JS -->
<script src="{% static './vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>
<script src="{% static './vendor/nouislider/distribute/nouislider.min.js' %}"></script>
<script src="{% static './vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static './vendor/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static './vendor/jarallax/dist/jarallax.min.js' %}"></script>
<script src="{% static './vendor/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static './vendor/jquery-countdown/dist/jquery.countdown.min.js' %}"></script>
<script src="{% static './vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static './vendor/prismjs/prism.js' %}"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% block javascript %}
{% endblock javascript %}
<script src="{% static './assets/js/neumorphism.js' %}"></script>
</body>
</html>

templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<footer class="d-flex pb-5 pt-6 pt-md-7 border-top border-light bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <p><strong>Neumorphism UI PRO</strong> is a premium Bootstrap UI Kit built based on the newest design
                    trend called Neumorphism.</p>
                <ul class="d-flex list-unstyled mb-5 mb-lg-0">
                    <li class="mr-2">
                        <a href="https://twitter.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="twitter social link"
                           data-toggle="tooltip" data-placement="top" title="Follow @themesberg on Twitter">
                            <span aria-hidden="true" class="fab fa-twitter"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="https://www.facebook.com/themesberg/" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="facebook social link"
                           data-toggle="tooltip" data-placement="top" title="Like @themesberg on Facebook">
                            <span aria-hidden="true" class="fab fa-facebook"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="https://github.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="github social link"
                           data-toggle="tooltip" data-placement="top" title="Open source projects">
                            <span aria-hidden="true" class="fab fa-github"></span>
                        </a>
                    </li>
                    <li>
                        <a href="https://dribbble.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="dribbble social link"
                           data-toggle="tooltip" data-placement="top" title="Follow us on Dribbble">
                            <span aria-hidden="true" class="fab fa-dribbble"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5>Themesberg</h5>
                <ul class="footer-links list-unstyled mt-2">
                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/blog">Blog</a></li>
                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/products">Products</a>
                    </li>
                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/about">About Us</a>
                    </li>
                    <li><a class="p-2" target="_blank" href="https://themesberg.com/contact">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5>Other</h5>
                <ul class="footer-links list-unstyled mt-2">
                    <li class="mb-1"><a class="p-2"
                                        href="https://themesberg.com/docs/pixel-bootstrap/getting-started/overview/"
                                        target="_blank">Docs
                        <span class="badge badge-gray text-uppercase ml-2">v1.0</span></a>
                    </li>
                    <li class="mb-1">
                        <a class="p-2" href="https://themesberg.com/docs/pixel-bootstrap/getting-started/changelog"
                           target="_blank">Changelog</a>
                    </li>
                    <li class="mb-1">
                        <a class="p-2" target="_blank" href="https://themesberg.com/licensing">License</a>
                    </li>
                    <li>
                        <a class="p-2" target="_blank"
                           href="https://github.com/themesberg/pixel-bootstrap-ui-kit/issues">Support</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-4 mb-5 mb-lg-0">
                <h5>Subscribe</h5>
                <p class="text-gray font-small mt-2">Join our mailing list. We write rarely, but only the best
                    content.</p>
                <form action="#">
                    <div class="form-row mb-2">
                        <div class="col-12">
                            <label class="h6 font-weight-normal d-none" for="exampleInputEmail3">Email address</label>
                            <input type="email" class="form-control mb-2" placeholder="example@company.com" name="email"
                                   aria-label="Subscribe form" id="exampleInputEmail3" required>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block" data-loading-text="Sending">
                                <span>Subscribe</span>
                            </button>
                        </div>
                    </div>
                </form>
                <p class="text-gray font-small m-0">We’ll never share your details. See our <a class="text-black"
                                                                                               href="#">Privacy
                    Policy</a></p>
            </div>
        </div>
        <hr class="my-5">
        <div class="row">
            <div class="col">
                <a href="https://themesberg.com" target="_blank" class="d-flex justify-content-center">
                    <img src="{% static './assets/img/themesberg.svg' %}" height="25" class="mb-3"
                         alt="Themesberg Logo">
                </a>
                <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                    <p class="font-weight-normal font-small mb-0">Copyright © Themesberg
                        <span class="current-year">2020</span>. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/home.html
<!--
=========================================================
* Neumorphism UI - v1.0.0
* Manipulated by nvd
=========================================================
-->
{% extends 'base.html' %}
{% load static %}

{% block application_title %}
    Persian Language Processing
{% endblock %}
{% block header_for_application %}
    <li><a class="dropdown-item" href="#API">APIs</a></li>
{% endblock %}
{% block application_content %}
    In this series, we have done applications related to text mining and word processing.
    In this system, you can see the performance of each application, test it yourself,
    and finally learn how to use this application in your system using the APIs that are available to you,
    and finally from it use.
{% endblock %}
{% block apllication_download_master %}
{% endblock %}
{% block main_body %}
    <!-- Section api -->
    <section class="section bg-primary pt-0 section-lg" id="API">
        <div class="container">
            <!-- Title -->
            <div class="row">
                <div class="col-md-4">
                    <div class="mb-5">
                        <span class="font-weight-bold">APIs</span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-12 col-md-12 col-lg-12">
                    <!--Accordion-->
                    <div class="accordion shadow-soft rounded" id="accordionExample1">
                        <div class="card card-sm card-body bg-primary border-light mb-0">
                            <a href="#panel-1" data-target="#panel-1" class="accordion-panel-header"
                               data-toggle="collapse"
                               role="button" aria-expanded="false" aria-controls="panel-1">
                                <span class="h6 mb-0 font-weight-bold">Add Data Set</span>
                                <span class="icon"><span class="fas fa-plus"></span></span>
                            </a>
                            <div class="collapse" id="panel-1">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        This section is under development.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--End of Accordion-->
                </div>
            </div>
        </div>
    </section>
    <!-- End of api -->
{% endblock %}

templates/keywords_extraction.html
<!--
=========================================================
* Neumorphism UI - v1.0.0
* Manipulated by nvd
=========================================================
-->
{% extends 'base.html' %}
{% block title %}|Keywords Extraction{% endblock %}
{% block header_for_application %}
    <li><a class="dropdown-item" href="#Test">Test</a></li>
    <li><a class="dropdown-item" href="#API">APIs</a></li>
{% endblock %}
{% block application_title %}Extract Keywords from Persian Documents{% endblock %}
{% block application_content %}In this research, we calculate keywords from Persian texts based on statistical methods
    and machine learning tools.{% endblock %}
{% block application_download_href %}#{% endblock %}
{% block main_body %}
    <!-- Section Test -->
    <section class="section bg-primary pt-0 section-lg" id="Test">
        <div class="container">
            <!-- Title -->
            <div class="row">
                <div class="col-md-4">
                    <div class="mb-5">
                        <span class="font-weight-bold">Test</span>
                    </div>
                </div>
            </div>
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12 col-lg-12 mb-5">
                    <!-- Contact Card -->
                    <div class="card bg-primary shadow-soft border-light p-2 p-md-3 p-lg-5" id="uncategorized_category">
                        <div class="card-header pb-0 text-center">
                            <h2 class="h1 mb-3">Keywords Extraction.</h2>
                            <p class="mb-5 lead">
                                Extract keywords related to your document by typing your document in the following
                                window.
                            </p>
                        </div>
                        <form class="col-12 col-md-8 mx-auto" method="post" id="news_for_test_performance_form">
                            <!-- Form -->
                            <div class="form-group">
                                <label for="exampleFormControlTextarea2">Document</label>
                                <textarea class="form-control" name="content_text_for_classify"
                                          id="content_news_for_test_performance_textarea"
                                          placeholder="Enter your document..."
                                          rows="10"></textarea>
                            </div>
                            <!-- End of Form -->
                            <div class="alert alert-info" id="category_title_empty"> Keywords:
                                <button class="btn btn-primary" type="button"
                                        id="classification_submited_loading" disabled style="visibility:hidden;">
                                        <span class="spinner-border spinner-border-sm" role="status"
                                              aria-hidden="true"></span>
                                    <span class="sr-only">Loading...</span>
                                </button>
                            </div>
                            <div class="px-0 mx-auto" style="margin-top: 10px">
                                <button type="submit" class="btn btn-primary">Extraction</button>
                            </div>
                        </form>
                        <div class="col-md-4">
                            <!-- Modal Content -->
                            <div class="modal fade" id="modal-default" tabindex="-1" role="dialog"
                                 aria-labelledby="modal-default" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h2 class="h6 modal-title mb-0" id="modal-title-default">Feedback</h2>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            If the category provided is incorrect, you can select the category
                                            you want to help better train the system. Thank you in advance for
                                            your cooperation.
                                            <form class="" method="post"
                                                  id="news_for_test_feedback_form">
                                                <div id="field_set_categories_list_name"></div>
                                                {% for cat_key, cat_val in categories_list_name.items %}
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="radio"
                                                               name="category_radios"
                                                               id="category_radios{{ cat_key }}"
                                                               value="{{ cat_key }}">
                                                        <label class="form-check-label"
                                                               for="category_radios{{ cat_key }}">
                                                            {{ cat_val }}
                                                        </label>
                                                    </div>
                                                {% endfor %}
                                                <!-- End of Radio -->
                                                </fieldset >
                                                <hr id="for_asign_news_pk">
                                                <button type="submit" class="btn btn-primary">Send
                                                </button>
                                                <button type="button" class="btn btn-primary text-danger ml-auto"
                                                        data-dismiss="modal" style="float: right">Close
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End of Modal Content -->
                        </div>
                    </div>
                    <!-- End of Contact Card -->
                </div>
            </div>
        </div>
    </section>
    <!-- End of Test -->
    <!-- Section api -->
    <section class="section bg-primary pt-0 section-lg" id="API">
        <div class="container">
            <!-- Title -->
            <div class="row">
                <div class="col-md-4">
                    <div class="mb-5">
                        <span class="font-weight-bold">APIs</span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-12 col-md-12 col-lg-12">
                    <!--Accordion-->
                    <div class="accordion shadow-soft rounded" id="accordionExample1">
                        <div class="card card-sm card-body bg-primary border-light mb-0">
                            <a href="#panel-1" data-target="#panel-1" class="accordion-panel-header"
                               data-toggle="collapse"
                               role="button" aria-expanded="false" aria-controls="panel-1">
                                <span class="h6 mb-0 font-weight-bold">Keywords Extraction</span>
                                <span class="icon"><span class="fas fa-plus"></span></span>
                            </a>
                            <div class="collapse" id="panel-1">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        This section is under development.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card card-sm card-body bg-primary border-light mb-0">
                            <a href="#panel-2" data-target="#panel-2" class="accordion-panel-header"
                               data-toggle="collapse"
                               role="button" aria-expanded="false" aria-controls="panel-1">
                                <span class="h6 mb-0 font-weight-bold">Feedback</span>
                                <span class="icon"><span class="fas fa-plus"></span></span>
                            </a>
                            <div class="collapse" id="panel-2">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        This section is under development. </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--End of Accordion-->
                </div>
            </div>
        </div>
    </section>
    <!-- End of api -->
{% endblock %}

{% block javascript %}
{% endblock javascript %}

templates/test.html
test